argument: Fix cppcoreguidelines-avoid-c-arrays
Suppress it, as switching to std::array<...> causes g++ to complain that
options has an incomplete type.

```
../argument.hpp:44:25: error: do not declare C-style arrays, use std::array<> instead [cppcoreguidelines-avoid-c-arrays,-warnings-as-errors]
    static inline const option options[] = {
                        ^
```

Change-Id: I6730bd7fce25eac3fbf23ea083928b8a98bafa35
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>