test: physical: Fix misc-unused-using-decls
```
../test/physical.cpp:74:18: error: using decl 'Throw' is unused [misc-unused-using-decls,-warnings-as-errors]
using ::testing::Throw;
                 ^
/home/andrew/src/openbmc/phosphor-led-sysfs/build/../test/physical.cpp:74:18: note: remove the using
using ::testing::Throw;
~~~~~~~~~~~~~~~~~^~~~~~
```

Change-Id: Ia13ce426cd366ea3c13f691fc1f1f93d1aa173ec
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>