controller: Fix bugprone-unused-raii
```
/home/andrew/src/openbmc/phosphor-led-sysfs/build/../controller.cpp:143:5: error: object destroyed immediately after creation; did you mean to name the object? [bugprone-unused-raii,-warnings-as-errors]
    sdbusplus::server::manager_t(bus, objPath.c_str());
    ^
                                 give_me_a_name
```

Change-Id: I4225f71874dbabfc315c4ba5d252d0d075868a68
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>